### ISSUE TITLE
Como usar??

### ISSUE THREAD

**Issue by danielfontenell** [ruanpiano/votacao-a-fazenda#1]
Eu quero usar ele como faço?

**Comment by ruanpiano** [comment]
Vou atualizar o README hoje.

**Comment by danielfontenell** [comment]
obg! vou esperar, ele é pra votar só na jojo ne?

**Comment by ruanpiano** [comment]
Exato.

README atualizado.

**Comment by danielfontenell** [comment]
Não consegui, estou usando o terminal do ubuntu no windows 10. Aparece esse erro: docker: Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?.
See 'docker run --help'.
